version: "3.8"

services:
  web:
    container_name: imgshare_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo/imgshare
  mongo:
    container_name: imgshare_mongo
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: json-file